export type CompletionFlowSlug =
  | "welcome" | "login" | "create-account" | "forgot-password" | "verification-code"
  | "password-reset-success" | "biometric-opt-in" | "edit-profile" | "change-photo" | "profile-saved"
  | "notification-primer" | "notification-preferences" | "appearance" | "dark-home" | "dark-cafe-detail"
  | "dark-settings" | "language" | "regional-format" | "sound-haptics" | "reduced-motion" | "accessibility"
  | "privacy-controls" | "location-permission" | "friend-visibility" | "blocked-accounts" | "export-data"
  | "export-requested" | "delete-account" | "delete-confirmation" | "two-factor-setup" | "two-factor-code"
  | "recovery-codes" | "two-factor-enabled" | "help-center" | "faq-detail" | "contact-support"
  | "safety-report" | "report-submitted" | "trial-confirmed" | "active-plan" | "renewal-details"
  | "cancel-plan" | "cancellation-confirmed" | "restore-success" | "restore-error";

export type CompletionFlowKind = "info" | "form" | "toggles" | "selection" | "profile" | "subscription" | "danger" | "success" | "error";
export type CompletionFlowTarget = CompletionFlowSlug | "home" | "settings" | "profile" | "onboarding" | "plus";

export type CompletionFlowRow = {
  label: string;
  value?: string;
  settingKey?: string;
};

export type CompletionFlow = {
  slug: CompletionFlowSlug;
  eyebrow: string;
  title: string;
  description: string;
  rows: CompletionFlowRow[];
  actionLabel: string;
  next: CompletionFlowTarget;
  kind: CompletionFlowKind;
  secondaryLabel?: string;
  secondaryNext?: CompletionFlowTarget;
};

const row = (label: string, value?: string, settingKey?: string): CompletionFlowRow => ({ label, value, settingKey });
const flow = (value: CompletionFlow): CompletionFlow => value;

export const completionFlows: Record<CompletionFlowSlug, CompletionFlow> = {
  welcome: flow({ slug: "welcome", eyebrow: "WELCOME TO SIDEQUEST", title: "Find a café that fits the moment.", description: "Discover by vibe, budget, and what you actually need today.", rows: [row("YOUR VIBE", "quiet focus · catch-up · cute date"), row("YOUR RANGE", "under ₱250 · within 30 minutes")], actionLabel: "Create my account", next: "create-account", secondaryLabel: "Already exploring? Log in", secondaryNext: "login", kind: "info" }),
  login: flow({ slug: "login", eyebrow: "LOCAL PREVIEW", title: "Pick up where you left off.", description: "Cloud accounts are not connected in this build. Continue to the profile stored on this device.", rows: [row("EMAIL", "you@example.com"), row("PASSWORD", "8 characters or more")], actionLabel: "Continue locally", next: "home", secondaryLabel: "Preview recovery", secondaryNext: "forgot-password", kind: "form" }),
  "create-account": flow({ slug: "create-account", eyebrow: "DEVICE PROFILE", title: "Make room for small adventures.", description: "Create a café passport stored only on this device. No cloud account is created.", rows: [row("DISPLAY NAME", "Your name"), row("EMAIL", "you@example.com"), row("PASSWORD", "8 characters or more")], actionLabel: "Continue locally", next: "biometric-opt-in", kind: "form" }),
  "forgot-password": flow({ slug: "forgot-password", eyebrow: "RECOVERY PREVIEW", title: "Preview password recovery.", description: "Email delivery is not connected. Validate an address to continue through the local walkthrough.", rows: [row("EMAIL", "you@example.com")], actionLabel: "Continue preview", next: "verification-code", kind: "form" }),
  "verification-code": flow({ slug: "verification-code", eyebrow: "LOCAL PREVIEW", title: "Enter the six-digit demo code.", description: "No email was sent. Use any six digits to validate this local interaction.", rows: [row("VERIFICATION CODE", "3 8 1 9 4 2")], actionLabel: "Validate demo code", next: "password-reset-success", kind: "form" }),
  "password-reset-success": flow({ slug: "password-reset-success", eyebrow: "PREVIEW COMPLETE", title: "The recovery interaction works.", description: "No cloud password or session was changed in this local build.", rows: [row("Storage", "Device only")], actionLabel: "Return to local sign in", next: "login", kind: "success" }),
  "biometric-opt-in": flow({ slug: "biometric-opt-in", eyebrow: "QUICK SIGN-IN", title: "Unlock with your phone.", description: "Use Face ID or fingerprint for faster local sign-in.", rows: [row("Biometric sign-in", "Stored securely by your device")], actionLabel: "Use biometrics", next: "onboarding", secondaryLabel: "Not now", secondaryNext: "onboarding", kind: "info" }),
  "edit-profile": flow({ slug: "edit-profile", eyebrow: "YOUR PROFILE", title: "Make it feel like you.", description: "Update what friends see and how SIDEQUEST personalizes discovery.", rows: [row("DISPLAY NAME"), row("HANDLE"), row("HOME AREA"), row("BIO")], actionLabel: "Save profile", next: "change-photo", kind: "profile" }),
  "change-photo": flow({ slug: "change-photo", eyebrow: "PROFILE PHOTO", title: "Choose your café passport photo.", description: "Pick from your device or keep your initials.", rows: [row("Photo library"), row("Take a photo"), row("Use initials")], actionLabel: "Use this photo", next: "profile-saved", kind: "info" }),
  "profile-saved": flow({ slug: "profile-saved", eyebrow: "PROFILE UPDATED", title: "Looking good.", description: "Your profile changes are saved on this device.", rows: [row("Visibility", "Friends only"), row("Profile", "Up to date")], actionLabel: "Return to profile", next: "profile", kind: "success" }),

  "notification-primer": flow({ slug: "notification-primer", eyebrow: "NOTIFICATION PREVIEW", title: "A little nudge, never noise.", description: "Push delivery is not connected in this build. You can still save which updates you would want.", rows: [row("New café openings"), row("Quest reminders"), row("Friend activity")], actionLabel: "Choose preferences", next: "notification-preferences", kind: "info" }),
  "notification-preferences": flow({ slug: "notification-preferences", eyebrow: "LOCAL PREFERENCES", title: "Choose what could reach you.", description: "These choices persist on this device; no push notification service is connected yet.", rows: [row("New cafés near me", undefined, "cafeNotifications"), row("Quest reminders", undefined, "questNotifications"), row("Friend requests", undefined, "friendNotifications"), row("Weekly discovery digest", undefined, "weeklyDigest")], actionLabel: "Save preferences", next: "settings", kind: "toggles" }),
  appearance: flow({ slug: "appearance", eyebrow: "APPEARANCE", title: "Make it feel like yours.", description: "Choose how SIDEQUEST looks across your phone. The choice is saved on this device.", rows: [row("Light", "light"), row("Dark", "dark"), row("Use device setting", "system")], actionLabel: "Apply appearance", next: "settings", kind: "selection" }),
  "dark-home": flow({ slug: "dark-home", eyebrow: "DARK MODE", title: "Coffee after hours.", description: "Your discovery feed, tuned for low light.", rows: [row("Soft Hours", "0.8 km"), row("Morrow Coffee", "1.4 km"), row("Blank & Bloom", "2.1 km")], actionLabel: "Explore nearby", next: "home", kind: "info" }),
  "dark-cafe-detail": flow({ slug: "dark-cafe-detail", eyebrow: "CAFÉ", title: "Afterglow Room", description: "Quiet corners, warm lamps, excellent pour-over.", rows: [row("Hours", "Open until 11:00 PM"), row("Reviews", "4.8 · 186 reviews"), row("Vibe", "Study-friendly · Late-night")], actionLabel: "Start a quest", next: "home", kind: "info" }),
  "dark-settings": flow({ slug: "dark-settings", eyebrow: "SETTINGS", title: "Your space, your rules.", description: "Account, preferences, privacy, and more.", rows: [row("Account & profile"), row("Notifications"), row("Appearance · Dark"), row("Privacy & safety"), row("SIDEQUEST+")], actionLabel: "Done", next: "settings", kind: "info" }),
  language: flow({ slug: "language", eyebrow: "LANGUAGE PREVIEW", title: "Save a language preference.", description: "The interface is currently available in English. This device-local choice prepares a future translated build.", rows: [row("English", "en"), row("Filipino", "fil"), row("日本語", "ja"), row("한국어", "ko")], actionLabel: "Save preference", next: "settings", kind: "selection" }),
  "regional-format": flow({ slug: "regional-format", eyebrow: "REGION", title: "Current local formats.", description: "This build currently uses kilometres, 12-hour time, and Philippine pesos.", rows: [row("Distance", "Kilometres"), row("Time", "12-hour"), row("Date", "Month / Day / Year"), row("Currency", "PHP")], actionLabel: "Done", next: "settings", kind: "info" }),
  "sound-haptics": flow({ slug: "sound-haptics", eyebrow: "FEEDBACK PREVIEW", title: "Save feedback preferences.", description: "These device-local choices are ready for future sound and haptic assets; this build does not trigger them yet.", rows: [row("App sounds", undefined, "appSounds"), row("Quest completion sound", undefined, "questSounds"), row("Button haptics", undefined, "buttonHaptics"), row("Celebration haptics", undefined, "celebrationHaptics")], actionLabel: "Save preferences", next: "settings", kind: "toggles" }),
  "reduced-motion": flow({ slug: "reduced-motion", eyebrow: "MOTION", title: "Move at your pace.", description: "Reduce animation without losing context.", rows: [row("Reduce motion", undefined, "reducedMotion"), row("Cross-fade transitions", undefined, "crossFadeTransitions"), row("Auto-play celebrations", undefined, "autoPlayCelebrations")], actionLabel: "Save motion", next: "settings", kind: "toggles" }),
  accessibility: flow({ slug: "accessibility", eyebrow: "ACCESSIBILITY", title: "Designed around you.", description: "Adjust text, contrast, motion, and navigation.", rows: [row("Larger text", undefined, "largerText"), row("High contrast", undefined, "highContrast"), row("Reduce motion", undefined, "reducedMotion"), row("Screen reader labels", undefined, "screenReaderLabels"), row("Color-blind friendly cues", undefined, "colorBlindCues")], actionLabel: "Save accessibility", next: "settings", kind: "toggles" }),

  "privacy-controls": flow({ slug: "privacy-controls", eyebrow: "PRIVACY", title: "Privacy, without mystery.", description: "Control what SIDEQUEST stores and shares.", rows: [row("Precise location", undefined, "preciseLocation"), row("Personalized discovery", undefined, "personalizedDiscovery"), row("Activity analytics", undefined, "activityAnalytics"), row("Friend suggestions", undefined, "friendSuggestions")], actionLabel: "Save privacy", next: "settings", kind: "toggles" }),
  "location-permission": flow({ slug: "location-permission", eyebrow: "LOCATION", title: "Find cafés around you.", description: "Location powers nearby discovery and active quests.", rows: [row("While using the app", undefined, "preciseLocation"), row("Background tracking", "Never used"), row("Manual city", "Always available")], actionLabel: "Save location choice", next: "privacy-controls", kind: "toggles" }),
  "friend-visibility": flow({ slug: "friend-visibility", eyebrow: "SOCIAL", title: "Choose who sees you.", description: "Set how your profile and activity appear.", rows: [row("Everyone", "public"), row("Friends only", "friends"), row("Private", "private")], actionLabel: "Save visibility", next: "privacy-controls", kind: "selection" }),
  "blocked-accounts": flow({ slug: "blocked-accounts", eyebrow: "SAFETY", title: "Blocked accounts", description: "Blocked people cannot find or contact you.", rows: [row("No blocked accounts"), row("How blocking works"), row("Review safety tools")], actionLabel: "Done", next: "privacy-controls", kind: "info" }),
  "export-data": flow({ slug: "export-data", eyebrow: "YOUR DATA", title: "Take your local data with you.", description: "Open your phone’s share sheet with a JSON copy of the data stored by this build.", rows: [row("Profile & preferences"), row("Saved cafés & collections"), row("Quest history"), row("Reviews; photo files are not embedded")], actionLabel: "Share local export", next: "export-requested", kind: "info" }),
  "export-requested": flow({ slug: "export-requested", eyebrow: "EXPORT OPENED", title: "Your local copy is ready.", description: "SIDEQUEST opened the device share sheet. Nothing was uploaded to a server.", rows: [row("Format", "JSON text"), row("Source", "This device")], actionLabel: "Back to privacy", next: "privacy-controls", kind: "success" }),
  "delete-account": flow({ slug: "delete-account", eyebrow: "ACCOUNT", title: "Delete your account?", description: "This permanently removes your profile and history.", rows: [row("Saved cafés and collections"), row("Quest history"), row("Friends and activity"), row("Subscription access")], actionLabel: "Continue to delete", next: "delete-confirmation", kind: "danger" }),
  "delete-confirmation": flow({ slug: "delete-confirmation", eyebrow: "FINAL CHECK", title: "This cannot be undone.", description: "Type DELETE to confirm permanent local account removal.", rows: [row("Removes", "Profile, collections, quests, and reviews on this device")], actionLabel: "Delete permanently", next: "welcome", secondaryLabel: "Keep my account", secondaryNext: "settings", kind: "danger" }),
  "two-factor-setup": flow({ slug: "two-factor-setup", eyebrow: "SECURITY PREVIEW", title: "Preview another lock.", description: "Authenticator enrollment needs a cloud account service. This walkthrough stores only a local demo preference.", rows: [row("1", "Review the setup interaction"), row("2", "Enter six demo digits"), row("3", "Keep sample recovery codes")], actionLabel: "Preview authenticator", next: "two-factor-code", kind: "info" }),
  "two-factor-code": flow({ slug: "two-factor-code", eyebrow: "VERIFY", title: "Enter your security code.", description: "Use the six digits from your authenticator app.", rows: [row("SECURITY CODE", "•  •  •  •  •  •"), row("Refresh", "Every 30 seconds"), row("Having trouble?")], actionLabel: "Verify code", next: "recovery-codes", kind: "form" }),
  "recovery-codes": flow({ slug: "recovery-codes", eyebrow: "KEEP THESE SAFE", title: "Your recovery codes", description: "Each code works once if you lose your authenticator.", rows: [row("SQ7P - 4K2M"), row("B9RX - 8D3A"), row("NC5T - 1W6Q"), row("JL8V - 9F2H")], actionLabel: "I saved these", next: "two-factor-enabled", kind: "info" }),
  "two-factor-enabled": flow({ slug: "two-factor-enabled", eyebrow: "SECURED", title: "Two-factor is on.", description: "Your account now has an extra layer of protection.", rows: [row("Authenticator app", "Active"), row("Recovery codes", "Saved"), row("Trusted devices", "1")], actionLabel: "Done", next: "settings", kind: "success" }),
  "help-center": flow({ slug: "help-center", eyebrow: "HELP CENTER", title: "What can we help with?", description: "Quick answers for cafés, quests, accounts, and more.", rows: [row("Using café discovery"), row("Starting and finishing quests"), row("Account & privacy"), row("SIDEQUEST+ billing"), row("Safety and reporting")], actionLabel: "Contact support", next: "contact-support", secondaryLabel: "Read a common answer", secondaryNext: "faq-detail", kind: "info" }),
  "faq-detail": flow({ slug: "faq-detail", eyebrow: "QUESTS", title: "How do quests work?", description: "Quests turn café visits into small, memorable missions.", rows: [row("1", "Choose a nearby quest"), row("2", "Check in at the café"), row("3", "Complete the prompt"), row("4", "Share or keep it private")], actionLabel: "That answered it", next: "help-center", kind: "info" }),
  "contact-support": flow({ slug: "contact-support", eyebrow: "SUPPORT", title: "Send us a note.", description: "Demo support messages stay on this device.", rows: [row("TOPIC", "Account help"), row("EMAIL", "you@example.com"), row("MESSAGE", "Tell us what happened")], actionLabel: "Send message", next: "help-center", kind: "form" }),
  "safety-report": flow({ slug: "safety-report", eyebrow: "REPORT", title: "Tell us what happened.", description: "Your report is private and would be reviewed by a safety team.", rows: [row("REASON", "Harassment"), row("ACCOUNT", "@username"), row("DETAILS", "Add context"), row("Block this account too", undefined, "blockReportedAccount")], actionLabel: "Submit report", next: "report-submitted", kind: "form" }),
  "report-submitted": flow({ slug: "report-submitted", eyebrow: "REPORT RECEIVED", title: "Thanks for speaking up.", description: "The demo records this report locally for the walkthrough.", rows: [row("Case", "SQ-2841"), row("Status", "Under review"), row("Blocked account", "Yes")], actionLabel: "Return home", next: "home", kind: "success" }),

  "trial-confirmed": flow({ slug: "trial-confirmed", eyebrow: "SIDEQUEST+", title: "Your trial starts now.", description: "Seven days of deeper discovery in this local demo.", rows: [row("Unlimited café filters"), row("Exclusive monthly quests"), row("Advanced collections"), row("Renews", "Sep 7 · ₱149/month")], actionLabel: "Start exploring", next: "home", kind: "subscription" }),
  "active-plan": flow({ slug: "active-plan", eyebrow: "YOUR PLAN", title: "SIDEQUEST+ is active.", description: "You have demo access to every premium perk.", rows: [row("Plan", "Monthly"), row("Price", "₱149/month"), row("Next billing", "Sep 7"), row("Payment", "Demo card · •••• 4242")], actionLabel: "Manage plan", next: "renewal-details", kind: "subscription" }),
  "renewal-details": flow({ slug: "renewal-details", eyebrow: "BILLING", title: "Next renewal", description: "Review the illustrative charge and payment method.", rows: [row("Amount", "₱149.00"), row("Date", "Sep 7, 2026"), row("Payment", "Demo Visa · •••• 4242"), row("Billing history")], actionLabel: "Return to plan", next: "active-plan", secondaryLabel: "Cancel plan", secondaryNext: "cancel-plan", kind: "subscription" }),
  "cancel-plan": flow({ slug: "cancel-plan", eyebrow: "BEFORE YOU GO", title: "Pause the adventure?", description: "You’ll keep demo access until the end of this billing period.", rows: [row("Premium filters"), row("Exclusive quests"), row("Advanced collections"), row("Reminder before renewal")], actionLabel: "Cancel SIDEQUEST+", next: "cancellation-confirmed", kind: "danger" }),
  "cancellation-confirmed": flow({ slug: "cancellation-confirmed", eyebrow: "PLAN UPDATED", title: "Your plan is cancelled.", description: "Demo premium access stays active until Sep 7.", rows: [row("Access ends", "Sep 7"), row("Further charges", "None"), row("Restart", "Anytime")], actionLabel: "Return to settings", next: "settings", kind: "success" }),
  "restore-success": flow({ slug: "restore-success", eyebrow: "RESTORED", title: "Welcome back to Plus.", description: "Your demo subscription and premium access are restored.", rows: [row("Plan", "Monthly"), row("Status", "Active"), row("Next billing", "Sep 7")], actionLabel: "Continue", next: "home", kind: "success" }),
  "restore-error": flow({ slug: "restore-error", eyebrow: "COULDN’T RESTORE", title: "We couldn’t find a purchase.", description: "This demo has no real store receipt. Try the local restore preview instead.", rows: [row("Store account", "Demo only"), row("Internet connection", "Not required"), row("Purchase receipt", "Not connected")], actionLabel: "Try demo restore", next: "restore-success", kind: "error" }),
};

export function getCompletionFlow(slug: string | string[] | undefined): CompletionFlow {
  const key = Array.isArray(slug) ? slug[0] : slug;
  return key && key in completionFlows ? completionFlows[key as CompletionFlowSlug] : completionFlows.welcome;
}
