import { Ionicons } from "@expo/vector-icons";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { Screen } from "@/components/screen";
import { quests } from "@/domain/catalog";
import { useConsumer } from "@/state/consumer-provider";
import { useAppTheme, type AppPalette } from "@/theme/app-theme";
import { radii, typography } from "@/theme/tokens";

export function QuestsScreen({ onOpen }: { onOpen(id: string): void }) {
  const { state } = useConsumer(); const { colors } = useAppTheme(); const styles = createStyles(colors);
  return <Screen><Text style={styles.kicker}>SIDEQUESTS · {state.xp} XP</Text><Text style={styles.title}>Do something small and memorable.</Text><Text style={styles.subtitle}>Low-pressure challenges made for the café you already wanted to visit.</Text><View style={styles.list}>{quests.map((quest, index) => { const active = state.activeQuestId === quest.id; const completed = state.completedQuestIds.includes(quest.id); return <Pressable key={quest.id} onPress={() => onOpen(quest.id)} style={styles.card}><View style={[styles.orbit, index === 1 && styles.sage]}><Ionicons name={completed ? "checkmark" : index === 0 ? "timer" : index === 1 ? "chatbubble-ellipses" : "footsteps"} size={24} color={colors.white} /></View><View style={styles.copy}><Text style={styles.reward}>{active ? `CONTINUE · STEP ${state.questStep + 1}` : completed ? "COMPLETED" : `+${quest.xp} XP · ${quest.durationMinutes} MIN`}</Text><Text style={styles.cardTitle}>{quest.title}</Text><Text style={styles.cardText}>{quest.description}</Text></View><Ionicons name="chevron-forward" size={20} color={colors.inkMuted} /></Pressable>; })}</View></Screen>;
}

const createStyles = (colors: AppPalette) => StyleSheet.create({ kicker: { color: colors.caramel, fontFamily: typography.bodyBold, fontSize: 10, letterSpacing: 1 }, title: { marginTop: 8, color: colors.espresso, fontFamily: typography.bodyBold, fontSize: 28, lineHeight: 34 }, subtitle: { marginTop: 7, color: colors.inkMuted, fontFamily: typography.body, fontSize: 12, lineHeight: 18 }, list: { gap: 12, marginTop: 22 }, card: { minHeight: 122, flexDirection: "row", alignItems: "center", gap: 13, padding: 15, borderWidth: 1, borderColor: colors.border, borderRadius: radii.lg, backgroundColor: colors.paper }, orbit: { width: 44, height: 44, alignItems: "center", justifyContent: "center", borderRadius: 10, backgroundColor: colors.caramel }, sage: { backgroundColor: colors.sage }, copy: { flex: 1 }, reward: { color: colors.caramel, fontFamily: typography.bodyBold, fontSize: 9, letterSpacing: .7 }, cardTitle: { marginTop: 4, color: colors.espresso, fontFamily: typography.bodyBold, fontSize: 17 }, cardText: { marginTop: 3, color: colors.inkMuted, fontFamily: typography.body, fontSize: 12, lineHeight: 18 } });
