import { Ionicons } from "@expo/vector-icons";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useState } from "react";
import { CafeCard } from "@/components/cafe-card";
import { Screen } from "@/components/screen";
import { StateView } from "@/components/state-view";
import { useCafes } from "@/data/cafe-provider";
import { useConsumer } from "@/state/consumer-provider";
import { useAppTheme, type AppPalette } from "@/theme/app-theme";
import { radii, typography } from "@/theme/tokens";

export function SavedScreen({ onOpenCafe }: { onOpenCafe(id: string): void }) {
  const { colors } = useAppTheme(); const styles = createStyles(colors);
  const { state, createCollection, renameCollection, deleteCollection, setCollectionVisibility } = useConsumer(); const [name, setName] = useState("");
  const [editingId, setEditingId] = useState<string | null>(null); const [draftName, setDraftName] = useState("");
  const [deletingId, setDeletingId] = useState<string | null>(null);
  const { cafes } = useCafes();
  const savedIds = new Set(state.collections.flatMap((collection) => collection.cafeIds)); const saved = cafes.filter((cafe) => savedIds.has(cafe.id));
  const deleting = state.collections.find((collection) => collection.id === deletingId);
  const finishRename = (collectionId: string) => {
    renameCollection(collectionId, draftName);
    setEditingId(null);
  };
  return <Screen><Text style={styles.kicker}>COLLECTIONS</Text><Text style={styles.title}>Keep the places worth remembering.</Text><Text style={styles.subtitle}>{state.collections.length} collections · {saved.length} saved cafés</Text>
    <View style={styles.create}><TextInput accessibilityLabel="New collection name" placeholder="New collection name" placeholderTextColor={colors.inkMuted} value={name} onChangeText={setName} style={styles.input} /><Pressable accessibilityState={{ disabled: !name.trim() }} disabled={!name.trim()} onPress={() => { createCollection(name); setName(""); }} style={[styles.add, !name.trim() && styles.disabled]}><Text style={styles.addText}>Create</Text></Pressable></View>
    {deleting ? <View accessibilityRole="alert" style={styles.confirm}><Text style={styles.confirmTitle}>Delete {deleting.name}?</Text><Text style={styles.confirmText}>{deleting.cafeIds.length} saved café{deleting.cafeIds.length === 1 ? "" : "s"} will return to your other collections when applicable.</Text><View style={styles.confirmActions}><Pressable onPress={() => setDeletingId(null)} style={styles.keep}><Text style={styles.keepText}>Keep collection</Text></Pressable><Pressable onPress={() => { deleteCollection(deleting.id); setDeletingId(null); }} style={styles.delete}><Text style={styles.deleteText}>Delete collection</Text></Pressable></View></View> : null}
    <View style={styles.collectionList}>{state.collections.map((collection) => <View key={collection.id} style={styles.collection}>
      {editingId === collection.id ? <><TextInput accessibilityLabel={`Rename ${collection.name}`} autoFocus value={draftName} onChangeText={setDraftName} onSubmitEditing={() => finishRename(collection.id)} returnKeyType="done" style={styles.renameInput} /><Pressable accessibilityLabel={`Cancel ${collection.name} rename`} onPress={() => setEditingId(null)} style={styles.iconButton}><Ionicons name="close" size={19} color={colors.inkMuted} /></Pressable><Pressable accessibilityLabel={`Save ${collection.name} name`} accessibilityState={{ disabled: !draftName.trim() || draftName.trim() === collection.name }} disabled={!draftName.trim() || draftName.trim() === collection.name} onPress={() => finishRename(collection.id)} style={[styles.iconButton, (!draftName.trim() || draftName.trim() === collection.name) && styles.disabled]}><Ionicons name="checkmark" size={19} color={colors.sage} /></Pressable></> : <><View style={styles.collectionCopy}><Text style={styles.collectionName}>{collection.name}</Text><Text style={styles.collectionMeta}>{collection.cafeIds.length} cafés · {collection.visibility}</Text></View><Pressable accessibilityLabel={`Toggle ${collection.name} visibility`} onPress={() => setCollectionVisibility(collection.id, collection.visibility === "private" ? "friends" : "private")} style={styles.iconButton}><Ionicons name={collection.visibility === "private" ? "lock-closed-outline" : "people-outline"} size={18} color={colors.caramel} /></Pressable><Pressable accessibilityLabel={`Rename ${collection.name}`} onPress={() => { setEditingId(collection.id); setDraftName(collection.name); }} style={styles.iconButton}><Ionicons name="create-outline" size={18} color={colors.espresso} /></Pressable><Pressable accessibilityLabel={`Delete ${collection.name}`} disabled={state.collections.length <= 1} onPress={() => setDeletingId(collection.id)} style={[styles.iconButton, state.collections.length <= 1 && styles.disabled]}><Ionicons name="trash-outline" size={18} color={colors.danger} /></Pressable></>}
    </View>)}</View>
    {saved.length === 0 ? <StateView title="Nothing saved yet." message="Save cafés from Home or Discover and they will appear here." /> : <View style={styles.list}>{saved.map((cafe) => <CafeCard key={cafe.id} cafe={cafe} preferences={state.preferences} compact onOpen={() => onOpenCafe(cafe.id)} />)}</View>}
  </Screen>;
}
const createStyles = (colors: AppPalette) => StyleSheet.create({ kicker: { color: colors.caramel, fontFamily: typography.bodyBold, fontSize: 10, letterSpacing: 1 }, title: { marginTop: 8, color: colors.espresso, fontFamily: typography.bodyBold, fontSize: 28, lineHeight: 34 }, subtitle: { marginTop: 7, color: colors.inkMuted, fontFamily: typography.body, fontSize: 12 }, create: { flexDirection: "row", gap: 8, marginVertical: 20 }, input: { flex: 1, minHeight: 48, paddingHorizontal: 13, borderWidth: 1, borderColor: colors.border, borderRadius: radii.md, color: colors.espresso, backgroundColor: colors.paper, fontFamily: typography.body }, add: { minWidth: 80, minHeight: 48, alignItems: "center", justifyContent: "center", borderRadius: radii.md, backgroundColor: colors.espressoSoft }, addText: { color: colors.white, fontFamily: typography.bodyBold, fontSize: 11 }, disabled: { opacity: .4 }, collectionList: { gap: 8, marginBottom: 20 }, collection: { minHeight: 66, flexDirection: "row", alignItems: "center", gap: 5, padding: 9, borderWidth: 1, borderColor: colors.border, borderRadius: radii.md, backgroundColor: colors.paper }, collectionCopy: { minWidth: 0, flex: 1, paddingHorizontal: 5 }, collectionName: { color: colors.espresso, fontFamily: typography.bodyBold, fontSize: 13, flexShrink: 1 }, collectionMeta: { marginTop: 2, color: colors.inkMuted, fontFamily: typography.body, fontSize: 10 }, renameInput: { minWidth: 0, flex: 1, minHeight: 44, paddingHorizontal: 8, borderBottomWidth: 1, borderBottomColor: colors.caramel, color: colors.espresso, fontFamily: typography.bodyMedium }, iconButton: { width: 44, height: 44, alignItems: "center", justifyContent: "center", borderRadius: 12, backgroundColor: colors.caramelMist }, list: { gap: 13 }, confirm: { marginBottom: 16, padding: 16, borderWidth: 1, borderColor: colors.danger, borderRadius: radii.md, backgroundColor: colors.paper }, confirmTitle: { color: colors.espresso, fontFamily: typography.displaySemibold, fontSize: 20 }, confirmText: { marginTop: 6, color: colors.inkMuted, fontFamily: typography.body, fontSize: 11, lineHeight: 17 }, confirmActions: { flexDirection: "row", gap: 8, marginTop: 14 }, keep: { flex: 1, minHeight: 46, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: colors.border, borderRadius: radii.md }, keepText: { color: colors.espresso, fontFamily: typography.bodyBold, fontSize: 10 }, delete: { flex: 1, minHeight: 46, alignItems: "center", justifyContent: "center", borderRadius: radii.md, backgroundColor: colors.danger }, deleteText: { color: colors.white, fontFamily: typography.bodyBold, fontSize: 10 } });
